tap 'aykamko/tag-ag'
tap 'homebrew/bundle'
tap 'lautis/refined-github-safari'
tap 'lyft/private-formulae git@github.com:lyft/homebrew-private-formulae.git
tap 'sberrevoets/formulae'

brew 'sberrevoets/formulae/urlview', args: ['HEAD']

brew 'black'
brew 'cask'
brew 'class-dump'
brew 'cocoapods'
brew 'coreutils'
brew 'ctags'
brew 'dduan/formulae/tre'
brew 'dockutil'
brew 'fd'
brew 'findutils' --with-default-names
brew 'fzy'
brew 'git'
brew 'gitstack' --HEAD
brew 'gnu-sed' --with-default-names
brew 'hub'
brew 'keith/formulae/tag'
brew 'lynx'
brew 'openssh'
brew 'openssl'
brew 'rbenv'
brew 'reattach-to-user-namespace' --with-wrap-pbcopy-and-pbpaste
brew 'refined-github-safari'
brew 'rename'
brew 'ruby-install'
brew 'set-simulator-location'
brew 'the_silver_searcher'
brew 'tmux'
brew 'vim'
brew 'zsh'
