tap 'aykamko/tag-ag'
tap 'homebrew/bundle'
tap 'sberrevoets/formulae'

brew 'sberrevoets/formulae/urlview', args: ['HEAD']

brew 'cask'
brew 'class-dump'
brew 'cocoapods'
brew 'coreutils'
brew 'ctags'
brew 'findutils' --with-default-names
brew 'git'
brew 'gnu-sed' --with-default-names
brew 'hub'
brew 'lynx'
brew 'openssh'
brew 'openssl'
brew 'rbenv'
brew 'reattach-to-user-namespace' --with-wrap-pbcopy-and-pbpaste
brew 'rename'
brew 'ruby-install'
brew 'keith/formulae/tag'
brew 'the_silver_searcher'
brew 'tmux'
brew 'vim'
brew 'zsh'
