tap 'homebrew/bundle'
tap 'sberrevoets/formulae'

brew 'sberrevoets/formulae/urlview', args: ['HEAD']

brew 'cask'
brew 'class-dump'
brew 'cocoapods'
brew 'hub'
brew 'lynx'
brew 'openssh'
brew 'openssl'
brew 'rbenv'
brew 'ruby-install'
brew 'tmux'
brew 'vim'
brew 'zsh'
